"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _page_home from './page-home.bones.json'
import _page_hub from './page-hub.bones.json'
import _page_search from './page-search.bones.json'
import _page_tasks from './page-tasks.bones.json'
import _page_dashboard from './page-dashboard.bones.json'
import _page_messages from './page-messages.bones.json'
import _page_notifications from './page-notifications.bones.json'
import _page_post from './page-post.bones.json'
import _page_profile from './page-profile.bones.json'
import _page_item_detail from './page-item-detail.bones.json'
import _page_login from './page-login.bones.json'
import _page_onboarding from './page-onboarding.bones.json'
import _shared_card_grid from './shared-card-grid.bones.json'

configureBoneyard({"animate":"shimmer"})

registerBones({
  "page-home": _page_home,
  "page-hub": _page_hub,
  "page-search": _page_search,
  "page-tasks": _page_tasks,
  "page-dashboard": _page_dashboard,
  "page-messages": _page_messages,
  "page-notifications": _page_notifications,
  "page-post": _page_post,
  "page-profile": _page_profile,
  "page-item-detail": _page_item_detail,
  "page-login": _page_login,
  "page-onboarding": _page_onboarding,
  "shared-card-grid": _shared_card_grid,
})
